# copied from https://github.com/ehemmerlin/svelter

version: "3.4"
services:
    chem:
        image: 627023082830.dkr.ecr.us-west-1.amazonaws.com/chem:latest
        build:
            # you need to have the context outside of web_app so you can copy ./scripts
            context: ~/toyprojs/chem_front/web_app
        # binding this volume should make changes in the container appear outside of it
        volumes:
          - type: bind
            source: ./web_app
            target: /web_app
        command: npm run dev
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
            # - PORT=8080
            # - HOST=0.0.0.0
        networks:
            mynet:

    nginx_rev:
        container_name: nginx_rev
        hostname: nginx_rev
        build:
            context: ~/toyprojs/chem_front/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/config:/etc/nginx
            - ./nginx/certs:/etc/ssl/private


networks:
    mynet:
        driver: bridge